### ISSUE TITLE
Bug Report: topicmap update requires deleting the statefulset

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1001]
### Expected Behavior

When changing the topicmap in the Helm chart, the pod should be restarted with the new environment variables

### Current Behavior

It is not restarted and the entire statefulset needs to be deleted and redeployed in order to get the new topimap

### Steps to Reproduce

1. CHange the topicmap in Helm Chart
2. See how it is not changed in the statefulset

### Context (Environment)

Venice project

### Version

v0.9.x

**Comment by Scarjit** [comment]
Cannot reproduced, just updated values in 1-8 using the helm release, and it instantly updated

**Comment by JeremyTheocharis** [comment]
Maybe then false alarm
