### ISSUE TITLE
The possibility to graphically display the shop floor with important KPIs at a glance

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#104]
Informations like:
-For each Station:
 - current Operator
 - current Order
 - current Produkt
 - KPIS (speed, OEE)
etc.

**Comment by Scarjit** [comment]
@krgrsebastian This issue seems to relate to your current Grafana plugin implementation.
Can you reference it in your PR, once you have finished it ?
