### ISSUE TITLE
Bug Report: cannot install Node-RED nodes

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1056]
### Expected Behavior

It should be possible to install additional Node-RED nodes. 

### Current Behavior

The installation takes forever.

### Steps to Reproduce

1. Install the stack
2. Try to install additional Node-RED nodes via the UI

### Context (Environment)

Various reported customer issues

### Possible Solution

Remove the init containers, which install various nodes. Because there are so many nodes installed by default it causes the installation to take forever (caused by npm). even the manual installation using npm takes forever (`npm install xxx`).

### Version

v0.9.x

**Comment by Scarjit** [comment]
Should we take out the default flows too ?
Cause they won't install correctly without those plugins ?
