### ISSUE TITLE
Allow all ia/raw/xxx messages to be transfered to Kafka

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1093]
**Is your feature request related to a problem? Please describe.**
Sometimes in makes sense to order the raw data in a different format and to be flexible in the topics

**Describe the solution you'd like**
For this we want to have all data in all ia/raw topics in Kafka using "High Throughput" logic. Right now it needs to follow a certain topic structure.

**Comment by Scarjit** [comment]
This requires a change to the documentation.
https://docs.umh.app/docs/concepts/mqtt/#topic-iaraw

**Comment by Scarjit** [comment]
New regex would look like this:

regexr.com/6lji2
