### ISSUE TITLE
Remove docs from code

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#1103]
**Is your feature request related to a problem? Please describe.**
Keeping docs inside the core repo bloats the repo and makes it less flexible for changes.

**Describe the solution you'd like**
Remove docs from this repo, once the new docs repo is finished.

**Comment by Scarjit** [comment]
@JeremyTheocharis Do we need another method for publishing or development.yaml, or has this already been solved ?

**Comment by JeremyTheocharis** [comment]
We would need a new method, but it makes sense to leave it in this repository and maybe only change the link

**Comment by Scarjit** [comment]
@JeremyTheocharis Now that we moved the development.yaml out of docs, can we go ahead and archive docs ?
