### ISSUE TITLE
As a customer I want the sensorconnect to be compatible with the old data model and with ARM

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#112]
I would like to be able to set sensorconnect to send data in the old data format.
![2021-02-08_16h34_10](https://user-images.githubusercontent.com/77407527/107242277-19452800-6a2c-11eb-9e71-97395e15c84a.png)

**Comment by Scarjit** [comment]
@kruegeralex Is this issue still relevant ?
