### ISSUE TITLE
Bug Report: raw messages fill up queue in kafka-to-postgres

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1121]
### Expected Behavior

Kafka-to-postgres should ignore all /raw messages

### Current Behavior

It receives them and then discards them at a later stage. This results in bloated logs and unnecesseraly keeping kafka-to-postgres busy.

### Steps to Reproduce

1. Send messages in /raw topic
2. Kafka-to-postgres will log every messages as it discards them

### Context (Environment)

v0.9.4-prerelease6

### Possible Solution

Maybe do not subscribe to /raw topics as kafka-to-postgres

### Version

v0.9.x

**Comment by Scarjit** [comment]
This will no longer happen with the default regex
