### ISSUE TITLE
Issue: timestamps not named consistently in prefix "modifyState"

### ISSUE THREAD

**Issue by Sphingobium** [united-manufacturing-hub/united-manufacturing-hub#1134]
### Expected Behavior

the start timestamp key should be named timestamp_ms and the end timestamp should be named timestamp_ms_end to be consistent with addShift nomenclature

### Current Behavior

start timestamp key is "start_time_stamp" and end timestamp is "end_time_stamp"

### Steps to Reproduce

open pxmodifyState.go  in kafka to postgres and look at the code

### Context (Environment)

none

### Version

v0.9.x

**Comment by Scarjit** [comment]
This change is breaking !
