### ISSUE TITLE
Add changeable default values

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1160]
**Is your feature request related to a problem? Please describe.**

In the values.yaml there are in general a lot of values, e.g., a request limit for cpu for barcodereader. If we change the default option  in a new version, e.g., increase the request limit, the change will only be included in new installations and not during upgrades.

**Describe the solution you'd like**
Default values should be specified in the Kubernetes templates and can be overridden with an entry in values.yaml (that is always uncommented). With this users can adjust single values, but will also profit from improved values during upgrades.

**Comment by Scarjit** [comment]
"(that is always uncommented)"

Wouldn't that prevent changes, since the default in template would never be used ?
