### ISSUE TITLE
Timescale can result in server failure due to high disk usage

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#1173]
### Expected Behavior

Timescale should automatically cleanup data like processValue after X days.

This can be done using timescales dataretention feature:
https://docs.timescale.com/timescaledb/latest/how-to-guides/data-retention/#data-retention=

### Current Behavior

Timescale does not cleanup old data, resulting in full disks.

### Steps to Reproduce

1) Setup stack
2) Add data ingestion
3) Wait

### Context (Environment)

Occurred on dev-server

### Possible Solution

https://docs.timescale.com/timescaledb/latest/how-to-guides/data-retention/#data-retention=

### Version

v0.9.x

**Comment by Scarjit** [comment]
@JeremyTheocharis We should discuss a good retention period for processValue

**Comment by Scarjit** [comment]
![image](https://user-images.githubusercontent.com/6317420/173595715-7f2ab26d-50fc-4ab5-856a-89b88fa7d8ce.png)
Before DELETE + VACUUM -> After

**Comment by JeremyTheocharis** [comment]
By default, we should not have a retention period as this might be unexpected for some customers.

**Comment by Scarjit** [comment]
https://github.com/united-manufacturing-hub/learn.umh.app/issues/21
