### ISSUE TITLE
Set default language of factoryinsight to english

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1175]
**Is your feature request related to a problem? Please describe.**
The default language is German, but most people will only be able to speak english. So the default format should be english.

**Describe the solution you'd like**
Set the default languageCode in the databsae to english

**Comment by Scarjit** [comment]
According to the DB creation statement, the default is already english.

https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/49c0d6847036df39d6140f76a1c7d801c3f95790/deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml#L162-L175

**Comment by Scarjit** [comment]
I'v found a bug inside FI, resulting in german language if no config is present, this is fixed in #1180
