### ISSUE TITLE
A new processValues takes minutes to arrive in Grafana, subsequent messages are fine

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1223]
### Expected Behavior

When sending new processValues, I want them to appear immediately in Grafana

### Current Behavior

It takes a couple of minutes until they appear in Grafana

### Steps to Reproduce

1. Create a new processValue and send a message
2. It will take a couple of minutes until it gets selectable in Grafana

### Context (Environment)

-

### Possible Solution

This is likely happening beause the topic creation process in Kafka takes too much time. Maybe we can speed that step up? If not possible, we should add a general warning in the documentation stating that the first message to any MQTT topic might take a couple of minutes to go initially though (but all subsequent messages will be sub-second). @Sphingobium 

### Version

v0.9.x

**Comment by Scarjit** [comment]
This should be fixable by lowering [metadata.max.age.ms](https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_metadata.max.age.ms)

**Comment by Scarjit** [comment]
@JeremyTheocharis Can you give me a good time, for metadata.max.age.ms ?
I don't want to go to low.

Azure uses [3 minutes](https://docs.microsoft.com/en-us/azure/event-hubs/apache-kafka-configurations), Confluent uses 5 minutes by default.

Going to low, could block other kafka operations and will increase load on the broker.

**Comment by Scarjit** [comment]
Let's use 3m
