### ISSUE TITLE
Unify logging handling

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#1244]
**Is your feature request related to a problem? Please describe.**
Currently every services has it's own method to setup zap logging.

**Describe the solution you'd like**
Move the code to a new module (this should be inside a new git repo, so our non-core services can also use it) and fix all services to use it.

**Comment by DaruZero** [comment]
Should that module be inside the umh-lib repo? Given that it should be for common code shared between our repositories, I think it should fit.
Otherwise I can create a umh-utils repo and upload the new module (and eventually other ones) in that

**Comment by Scarjit** [comment]
@DaruZero The umh-lib was an experiment, but it is quite outdated, just make a new repo

**Comment by DaruZero** [comment]
Is umh-utils a suitable name?

**Comment by JeremyTheocharis** [comment]
Discussion: structured, leveled logging - https://github.com/golang/go/discussions/54763
