### ISSUE TITLE
Using quotation marks in processValues will not return an error, but will also not save the message

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1266]
This message here will not be stored, but it will also not throw an error message in kafka-to-postgresql. The message was added via Node-RED into MQTT. 

![image](https://user-images.githubusercontent.com/30755722/191283832-eeef8abc-fb4c-4a7d-bcb6-2269e7c48904.png)

See also:
https://umhhelp.zendesk.com/agent/tickets/136

**Comment by Scarjit** [comment]
Can you show me the actual json ?

**Comment by JeremyTheocharis** [comment]
You see the json above in the image. just think of the required {} and ,

{
  "timestamp_ms": 56465465,
....
}

**Comment by Scarjit** [comment]
@JeremyTheocharis The problem is, that I don't trust the js console print to represent the generated json correctly.

But the real reason here is, that a string is not an integer (at least not for go), therefor it was dropped, due to being unparsable.

**Comment by JeremyTheocharis** [comment]
Can we ensure that we get error messages in these cases where messages are dropped due to being unparsable?
