### ISSUE TITLE
Update stack to go 1.19.4

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#1375]
### Expected Behavior

Go 1.19.4 was released yesterday (https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU)
We should update.

### Current Behavior

Stack runs on 1.19.3 or earlier

### Steps to Reproduce

-

### Context (Environment)

-

### Version

not applicable

**Comment by krgrsebastian** [comment]
Updated automatically.
