### ISSUE TITLE
Replace kafka in go with samara kafka

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#1438]

**Comment by DaruZero** [comment]
- [x] barcodereader https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/1580
- [ ] kafka-bridge
- [x] kafka-init https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/1583
- [ ] kafka-to-postgresql
- [x] mqtt-kafka-bridge https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/1491
- [ ] sensorconnect
