### ISSUE TITLE
As a user, I would like to be able to display the current production speed.

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#148]
Provide a general summary of the issue in the Title above

## Expected Behavior

If the line is currently not producing I want to get back the production speed 0 and not the last one it produced at.
I also don't want the last production speed to fluctuate as much as the current minute is added up --> maybe the last 60 seconds should be considered for the last value.

## Current Behavior

![image](https://user-images.githubusercontent.com/77407527/109539730-ef7aa080-7ac1-11eb-9d7f-2c9169fc5511.png)

When I return the last value, it is the one that was last produced, regardless of how long ago that was. This also distorts the average production speed if the last values (standstill) are not included.

**Comment by Scarjit** [comment]
Is this still relevant @kruegeralex ?
