### ISSUE TITLE
Fine-tune resources requests

### ISSUE THREAD

**Issue by DaruZero** [united-manufacturing-hub/united-manufacturing-hub#1554]
**Is your feature request related to a problem? Please describe.**

Currently the sum of all the resources requests adds up to more than 4Gi, our minimum system requirement recommended.

**Describe the solution you'd like**

Fine-tune the configuration so that the sum of memory and CPU does not exceeds 2 cores and 4Gi

**Describe alternatives you've considered**

**Additional context**

**Comment by JeremyTheocharis** [comment]
+ additionally can handle 500 msg/sec for the Historian Feature
