### ISSUE TITLE
Add persistent queue to prevent dataloss

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#161]
**Is your feature request related to a problem? Please describe.**
When mqtt-to-postgresql crashes the data between restart and crash is lost. Furthermore, when there are duplicates the entire 1s block from count and processValue is scrapped entirely. 

**Describe the solution you'd like**
Instead all failed messages should be stored to a queue and then tried to enter bit by bit. ALso all incoming messages should always be stored in a persistent queue first.

**Comment by Scarjit** [comment]
No longer relevant with kafka
