### ISSUE TITLE
Document that 0.9.14 requires SSE4.1

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#1615]
### Expected Behavior 🌈

Document that 0.9.14 requires SSE4.1

### Current Behavior 💥

Document that 0.9.14 requires SSE4.1

### Steps to Reproduce 🔍

Document that 0.9.14 requires SSE4.1

### Context (Environment) 🌎

Document that 0.9.14 requires SSE4.1

### Version 📦

v0.4.x

**Comment by DaruZero** [comment]
This issue should be in [umh.docs.umh.app](https://github.com/united-manufacturing-hub/umh.docs.umh.app)

**Comment by Scarjit** [comment]
yes
