### ISSUE TITLE
Sarama-Kafka-Wrapper not found

### ISSUE THREAD

**Issue by GirishBhutiya** [united-manufacturing-hub/united-manufacturing-hub#1798]
### Expected Behavior 🌈

Module not found.

### Current Behavior 💥

github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper/pkg/kafka: module github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper@latest found (v1.13.0), but does not contain package github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper/pkg/kafka

### Relevant log output 📝

```shell
github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper/pkg/kafka: module github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper@latest found (v1.13.0), but does not contain package github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper/pkg/kafka
```

### Steps to Reproduce 🔍

Clone app. 
Navigate to golang folder. 
Command : go mod tidy

### Context (Environment) 🌎

Ubuntu

### Version 📦

v0.9.x

**Comment by Scarjit** [comment]
github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper is no longer in use, check out https://github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper-2
