### ISSUE TITLE
Add benchmarks for data insertion, buffering, etc. into documentation

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#181]
Conduct or find benchmarks on e.g.,:

1. maximum MQTT messages (size, amount) of VerneMQ
2. INSERT performance (mqtt-to-postgres + database)
3. QUERY performance (factoryinsight + database)

We receive very often the question: How scalable is the United Manufacturing Hub?

Our answer should be, that a manufacturing company will never reach the limits (even with 300 - 500 machines sending each 50 msg / sec)

**Comment by Scarjit** [comment]
Notes:

VerneMQ/MQTT 5
 - VerneMQ has an recommendet loadtesting tool (https://docs.vernemq.com/guides/loadtesting, http://satori-com.github.io/mzbench/)
 - MQTT 5 uses an "Variable Byte Integer" (https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901011) to encode the message size (https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901011), therefore the theoretical maximum is 268,435,455 byte (~256 MB).
 - According to the MQTT 5 spec, both client and server have to set an allowed maximum size (https://docs.vernemq.com/configuration/nonstandard)

**Comment by Scarjit** [comment]
Depends on #54 and #52
