### ISSUE TITLE
Add read-only configuration widget to Grafana, so the customer can see their customer specific configuration

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JeremyTheocharis** [comment]
@Scarjit Still relevant. Add an endpoint in factoryinsight to view customer specific configuration

**Comment by Scarjit** [comment]
Closed, see: https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/1425
