### ISSUE TITLE
Add documentation on how to connect with timescaleDB

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#213]
As a user I would like to have the possibility to connect directly to the SQL database.

**Comment by Scarjit** [comment]
Fixed, see https://www.notion.so/united-manufacturing-hub/ab58fbca87834bfeb7f654af1dbb43fd?v=61b50b6953fd415bb2ac4dc5dccfc109&p=5004548145c04515a329703ca3a621c4&pm=s
