### ISSUE TITLE
Support for Ethernet/IP (CIP) PLCs

### ISSUE THREAD

**Issue by alphabet5** [united-manufacturing-hub/united-manufacturing-hub#244]
**Is your feature request related to a problem? Please describe.**
Support for Allen Bradley PLC's using Ethernet/IP. Most of the PLC's I deal with (in North America) are AB ControlLogix or CompactLogix. Support for these PLC's without having to convert from Ethernet/IP to OPCUA (using ignition, kepware, ftlinx, etc.) would be idea.

**Describe the solution you'd like**

**Describe alternatives you've considered**
kepware/ignition/ftlinx for enip->opcua seems like it would be the alternative. Built-in support would be excellent. 

**Additional context**
[libplctag](https://github.com/libplctag/libplctag) could be used. They provide an example wrapper in go that could be used, and the licensing would be compatible as far as I can tell.

**Comment by JeremyTheocharis** [comment]
Hi, thank you for the idea!

For connecting machines we are typically using node-red, as it is open source and has a lot of community built interfaces (like OPC/UA). There is also a node available that looks exactly like what you need: https://flows.nodered.org/node/node-red-contrib-cip-ethernet-ip

Have you tried that? As we do not have a PLC on hand we are currently unavailable to test it ourselves and therefore it is not included by default.

**Comment by alphabet5** [comment]
I will give it a try. I missed the part where node red is being used for the plc communication. Typically this is avoided due to performance reasons. 

For a typical site we are reading ~5-20k tags/second from a half dozen PLC's to historize the values, along . Unoptimized instances of polling these PLC's will, and have pegged the CPU leading to downtime. 

I'll see if I can get a test instance setup and do some performance testing. Thanks!

**Comment by JeremyTheocharis** [comment]
Fully agreed! node-red or Javascript in general is not designed for performance. For everything that we routinely do in node-red we write a entire seperate microservice like sensorconnect, which do it way more performant.

**Comment by JeremyTheocharis** [comment]
@alphabet5 Any feedback?

@kruegeralex Didn't our customer in brazil successfully use Ethernet IP using the node-red flow? If yes, we should add that to the documentation and then we can close this issue.

**Comment by alphabet5** [comment]
I haven't had a chance to do any testing yet. If you have documentation for it that would be great.

**Comment by kruegeralex** [comment]
Our customer had not used ethernet-ip but used: https://flows.nodered.org/node/node-red-contrib-pccc
to read out his Rockwell PLC. This worked without any problems

**Comment by Scarjit** [comment]
Should be fixed by integrating Benthos.
Please re-open if not.
