### ISSUE TITLE
IFM Sensor O1D108 is not processed automatically

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#289]
Provide a general summary of the issue in the Title above

## Expected Behavior

when i connect this sensor i want to get automatically the interpreted values (distance etc.)

## Current Behavior

Tell us what happens instead of the expected behavior

The service returns the values only as value_string

**Comment by Scarjit** [comment]
@kruegeralex Is this still an issue with sensorconnect ?

**Comment by Scarjit** [comment]
Is this still relevant @kruegeralex ?

**Comment by EmlingerM** [comment]
I could reproduce this issue. The problem is that all values, regardless of their actual type, are being returned in the JSON payload as strings.

```json
{
   "Distance":"47",
   "Switch state [OUT1]":"1",
   "connected":"connected",
   "timestamp_ms":"1728629682975",
   "type":"Io-Link"
}
```

Regarding https://umh.docs.umh.app/docs/datamodel/messages/_historian/#message-structure, the payload should look like this:

```json
{
   "Distance": 47,
   "Switch state [OUT1]": true,
   "connected":"connected",
   "timestamp_ms": 1728629682975,
   "type":"Io-Link"
}
```
