### ISSUE TITLE
Add microservice that automatically extracts all OPC/UA data and puts them into MQTT

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#295]
Example: 

- Python: https://github.com/FreeOpcUa/opcua-asyncio/blob/master/examples/client-subscription.py
- C: https://github.com/open62541/open62541/blob/master/examples/client_subscription_loop.c
- Golang: https://github.com/gopcua/opcua

**Comment by kruegeralex** [comment]
Problem is still present, because with the current implementation in Node-RED there are regularly disconnections, which can only be solved by restarting the flow.

**Comment by Scarjit** [comment]
Fixed with Benthos
