### ISSUE TITLE
Add processValueString Topic to 2nd level Data

### ISSUE THREAD

**Issue by larswitte** [united-manufacturing-hub/united-manufacturing-hub#303]
Regarding issue: #297

**Problem:**
MQTT topic processValue only used with int and float. There is no option to store string process values.

**Possible Solution**
Add processValueString MQTT Topic to UMH datamodel and add table processValueStringTable (instead of DOUBLE PRECISION datatype use TEXT or VARCHAR for value column).

**Comment by Scarjit** [comment]
Integrated in pull #506  (https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/506/commits/fb6a89af5eb913c33e5fd84ec1d60b45cc9afe1e)
