### ISSUE TITLE
Add cameraconnect

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#317]
Cameraconnect takes pictures from Industrial Cameras using Cognex and GenICam protocol and sends them to MQTT.

## Requirements
- connects to Cognex and GenICam cameras and retrieves images
- sends MQTT messages (see also #261 and #262)
- can be written in Python, prefered language is golang (for higher runtime stability)
- will be moved into a Docker container. 
- logs to the terminal

## Definition of done

- The service can handle up to 10 images per second, preferably 100
- It runs across multiple device restarts and at least for 48h continiously
- When it encounters a fatal error it will crash and will then be automatically restarted by Kubernetes
- The folder with all the source code will be called `/cameraconnect` and the Dockerfiles will be in `/deployment/cameraconnect`
- An automated build pipeline using Docker will be setup 
- There is a documentation in the docs similar to https://docs.umh.app/docs/developers/factorycube-edge/sensorconnect/
- It must be entirely configurable via environment variables
- There are Kubernetes files available for factorycube-edge and it is included in the Helm chart

This issue needs to be split up into multiple smaller issues during the development sprint.

**Comment by JonaVo** [comment]
Hi, thanks for the great summary. I added some minor changes. Looking forward to our developing session ;)

Cameraconnect takes pictures from Industrial Cameras using  GenICam protocol and sends them to MQTT.

### Requirements

- connects to cameras manufactured by Basler and AlliedVision which are using the GenICam standard and retrieves images
- sends MQTT messages (see also Rework data model for image and image recognition #261 and Rework data model for image and image recognition #262)
- acquiring and sending images can be triggered either via MQTT message or automatically by a given frequency
- can handle rgb and mono8 cameras
- can handle resolutions up to 4000x4000
- can be written in Python, prefered language is golang (for higher runtime stability)
- will be moved into a Docker container.
- logs to the terminal

### Definition of done

- The service can handle up to 10 images per second, preferably 100
- It runs across multiple device restarts and at least for 48h continuously
- When it encounters a fatal error it will crash and will then be automatically restarted by Kubernetes
- The folder with all the source code will be called /cameraconnect and the Dockerfiles will be in /deployment/cameraconnect
- An automated build pipeline using Docker will be setup
- There is a documentation in the docs similar to https://docs.umh.app/docs/developers/factorycube-edge/sensorconnect/
- It must be entirely configurable via environment variables
- There are Kubernetes files available for factorycube-edge and it is included in the Helm chart
- This issue needs to be split up into multiple smaller issues during the development sprint.

### Variables provided by the module user 

- Serial number of camera (to decide which camera gets picked if multiple are available)
- resolution of image (can be used to crop the image)
- offset of image in x and y axis (in case the camera should only send a specific section of the image)
- exposure time
- trigger frequency (for self-timer)
- color mode (mono8 or rgb)
