### ISSUE TITLE
Bug: Incomplete documentation for setting up on k3os, when using default bios date

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#321]
Documentation is missing solution to solve certificate errors, related to certificate date being in the future, on manual deployment.

## Expected Behavior

k3os should be able to start, when following [docs/getting-started/setup-development/](https://docs.umh.app/docs/getting-started/setup-development/)

## Current Behavior

k3os reports errors, due hardware date being in the past. (ex: 01.01.2017)

## Possible Solution

Load cloudconfig with added ntp_servers on OS install.

## Steps to Reproduce

1. Install k3os, without updating BIOS clock
2. Install UMH
3. helm will fail on **Install factorycube-server** step, due to outdated certificates.

## Detailed Description
 - Add documentation detailing how to load cloud config from http server.
 - Add sample config, with added k3os->ntp_server keys.

**Comment by JeremyTheocharis** [comment]
important: do not use HTTPS to host cloudinit file as you will get the same issue.
