### ISSUE TITLE
Remove Grafana datasources

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#330]
We should remove the Grafana datasources once we have moved everything to https://github.com/united-manufacturing-hub/united-manufacturing-hub-datasource

**Comment by JeremyTheocharis** [comment]
Additionally, we need to automatically update `deployment/factorycube-server/grafanaDatasource/plugin.zip`

**Comment by Scarjit** [comment]
> Additionally, we need to automatically update `deployment/factorycube-server/grafanaDatasource/plugin.zip`

Do we really need to update that ?
Our values.yaml in factorycube-server automatically pulls the latest release of both plugins:
https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/main/deployment/factorycube-server/values.yaml#L1006

**Comment by JeremyTheocharis** [comment]
You are right!

**Comment by Scarjit** [comment]
The only remaining traces of Grafana inside this repo are grafana-proxy, documentation & helm charts.
Therefore i don't see any remaining work for this issue.
