### ISSUE TITLE
Doc changes for MQTT Topics

### ISSUE THREAD

**Issue by Gornoka** [united-manufacturing-hub/united-manufacturing-hub#334]
Change topics for MQTT in docs, moving away from using /topic to show subtopics

change topics like ./addTOPIC to ./add/TOPIC to allow implementation of ./modify/TOPIC etc.

**Comment by JeremyTheocharis** [comment]
Let's also take a look athe following project for documenting and maybe even boilerplate code:

https://github.com/asyncapi/generator

**Comment by JeremyTheocharis** [comment]
https://github.com/asyncapi/go-template

**Comment by JeremyTheocharis** [comment]
Maybe use other specifications: https://sparkplug.eclipse.org/about/faq/

**Comment by JeremyTheocharis** [comment]
https://forums.opto22.com/t/sending-mqtt-sparkplug-b-control-messages-from-node-red/3478

**Comment by Scarjit** [comment]
Basically what the new datamodel does
