### ISSUE TITLE
Add capability for grafana-proxy to handle multiple API keys

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#383]
**Is your feature request related to a problem? Please describe.**
Currently only the API key for the default organisation is used. 
https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/aa03960fdc7df72c1e451f35502253d233bfd8e6/deployment/factorycube-server/templates/grafana-proxy.yaml#L52-L56

**Describe the solution you'd like**
We should enable all customer keys to be used. See also
https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/a8b983129f2b5378eb3f43b5a26b7e8c7ecc36c9/deployment/factorycube-server/templates/factoryinsight-deployment.yaml#L76-L91

**Comment by Scarjit** [comment]
Is this still relevant @JeremyTheocharis  ?
