### ISSUE TITLE
Grafana secret password incorrect, after helm update

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#385]
Helm upgrade changes grafana admin-password, without changing it in grafana's database

## Expected Behavior

Grafana database password shouldn't change on helm upgrade or be set correctly

## Steps to Reproduce

1. Setup stack
2. Use helm upgrade
3. The new admin-password won't work anymore

**Comment by JeremyTheocharis** [comment]
Cannot reproduce, which is strange because I encountered that error myself. Closing until problem can be safely reproduced.
