### ISSUE TITLE
few minor changes in docs

### ISSUE THREAD

**Issue by JonaVo** [united-manufacturing-hub/united-manufacturing-hub#395]
**1. Please add something like: change namespace in Lens to observe the cluster starting up, otherwise nothing will be displayed in Lens**

> ![image](https://user-images.githubusercontent.com/45003256/127486894-93128593-0b8c-428c-898f-3a9eccc04f8e.png)

______________________________________________________________
**2. Add a description how one can get the developement_values.yaml file via wget to simplify the process**

> ![image](https://user-images.githubusercontent.com/45003256/127487200-7da72a88-ff82-4a3b-823f-359f70208a2c.png)

______________________________________________________________
**3. Please change to "an edge device"**

> ![image](https://user-images.githubusercontent.com/45003256/127486707-632de3a2-4eb7-4a89-98ac-28fde9b361f5.png)

**Comment by JonaVo** [comment]
**Please remove cognex, as only GenICams are supported**

> ![image](https://user-images.githubusercontent.com/45003256/127496097-001286bd-8bea-4f11-8918-4e0bfc199238.png)

**Comment by Scarjit** [comment]
Tracked on https://github.com/united-manufacturing-hub/united-manufacturing-hub/tree/395-few-minor-changes-in-docs
