### ISSUE TITLE
OrderTimeline: I want to get back no order when in the selected Timerange is noOrder

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#42]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i ask factoryinsight for the orderTimeline and i get null back when there are noOrders in the selected timerange.

**Describe the solution you'd like**
I want to get back noOrder when there is no Order

**Comment by Scarjit** [comment]
Is this still relevant @kruegeralex ?
