### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by staanla** [united-manufacturing-hub/united-manufacturing-hub#450]
[https://docs.umh.app/docs/getting-started/understanding-the-technologies/#mqtt](https://docs.umh.app/docs/getting-started/understanding-the-technologies/#mqtt)
"UMH datamodel" link at paragraph end is broken.
Should likely go to [https://docs.umh.app/docs/concepts/mqtt/](https://docs.umh.app/docs/concepts/mqtt/) instead

**Comment by JeremyTheocharis** [comment]
Thank you for opening the issue! We will fix it in our next development sprint.
