### ISSUE TITLE
mqtt-to-postres: add productTagList, productTagStringList

### ISSUE THREAD

**Issue by larswitte** [united-manufacturing-hub/united-manufacturing-hub#460]
**Problem**
Currently mqtt-to-postgres will implement the functionality to receive single MQTT Messages under the `productTag` and `productTagString` topic (issue #331). Those messages always contain one name/value pair. As @Gornoka noted, this is great for flexibility but doesn't allow to verify the complete parsing of multiple name/value pairs in the postgresql db.

**Existing flow**
Original message:
``` json
{
  resolutionX: 400
  resolutionY: 300
  result: "scrap"
  timestamp_ms: 2132344
  AID: "asa12398"
}
```
broken into individual productTags/productTagStrings, example:
``` json
{
  valueName: "resolutionX"
  value: 400
  timestamp_ms: 2132344
  AID: "asa12398"
}
```
...

**Solution**
Add the topics `productTagList` and `productTagStringList` to the mqtt messages. Now enable mqtt-to-postgres to write always one complete message for one product/combined measurement into postgres and check, if the complete list was actually correctly parsed. This migth be very useful in cases, where complete datasets are absolutely necessary.

**Comment by Scarjit** [comment]
mqtt-to-postgresql is deprecated
