### ISSUE TITLE
New Grafana datasource plugin does not work automatically when setting up the latest version of factorycube-server

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#467]
New Grafana datasource plugin does not work automatically when setting up the latest version of factorycube-server

## Expected Behavior

When setting up factorycube-server one should see the example generated data from Node-RED in Grafana.

## Current Behavior

Grafana does not see them and when clicking on the plugin you can see that the URL is missing. Furthermore, when entering the correct service name / URL Grafana answers with Unexpected Error.

This should be a hotfix called v0.5.1

**Comment by Scarjit** [comment]
Related: https://github.com/united-manufacturing-hub/united-manufacturing-hub/issues/402
