### ISSUE TITLE
Querying images by Associated product tags and limiting the output number

### ISSUE THREAD

**Issue by Gornoka** [united-manufacturing-hub/united-manufacturing-hub#469]
**Is your feature request related to a problem? Please describe.**
Requesting image data for particular product classes or unknown timeframes results in large overhead in network transfer and parsing time.

**Describe the solution you'd like**
Function to allow querying image metadata with more params such as Number of images received and associated product tags 
( e.g. usefull for querying just images of Scrap or other quality classes)

**Describe alternatives you've considered**
Querying the api and metadata of the current paths leads to much overhead, especailly for applications where only the last image of a given class is interesting, since the time frame to query can not be determined without more informations ( e.g. searching for an image of a rare class, would result in an large amounts of unnecessary metadata)

**Comment by Scarjit** [comment]
It this still relevant ?

**Comment by Gornoka** [comment]
The situation still persists, so searching images is basically not possible with the current API(AFAIK).

**Comment by Scarjit** [comment]
Blobstorage is deprecated
