### ISSUE TITLE
I would like to use the system more easily in continuous production 

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#48]
**Is your feature request related to a problem? Please describe.**
Currently, the system is based on the size count to describe the production of an asset. This is designed as a discrete quantity. As a quantity above there is the "discrete product" here an equivalent for the continuous production is missing. Specifically, I would like to measure the good production on a weaving machine and subsequently be able to mark a part as bad production.

**Describe the solution you'd like**
 Specifically, I would like to measure the good production on a weaving machine and subsequently be able to mark a part as bad production.

**Comment by JeremyTheocharis** [comment]
@Scarjit This means allowing a float in  count messages, so that count (or the equivalent in the new datamodel) can be used to say "now 0.2m more have been produced", "now again 0.1m", etc.
