### ISSUE TITLE
Factorysimulator for testdata and integration tests

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#496]
**Is your feature request related to a problem? Please describe.**
As a mechanical engineer I want to have example data in the dashboard when starting up the stack for presentations and testing. Furthermore, as a mechanical engineer I would be great to have a reference architecture with sample code

Additionally, as developer I want to ensure that once a functionality is implemented that it does not break in the future (--> Integration test on each PR)

**Describe the solution you'd like**
A microservice called `factorysimulator`, which simulates a nonexisting factory. It needs to use all MQTT messages and cover all edge cases.

This could be either Python microservice or Node-RED in a second instance (prefered).

**Additional context**

Fixes #491 and refers to #495 
Fixes #449 
Fixes #432 

Refers to #493

**Comment by larswitte** [comment]
This is my current simulation for two production steps in node red to test digital shadow functionality (#297):

[{"id":"e259d00c.c234f8","type":"tab","label":"IntegrationTest1: AddProducts","disabled":false,"info":"Execute this flow first. Maybe set Mqtt out node username to TESTING"},{"id":"23ae98e1.65e538","type":"tab","label":"IntegrationTest2: ExampleStation","disabled":false,"info":"Execute second."},{"id":"d81eab1a.cff018","type":"mqtt-broker","name":"","broker":"factorycube-server-vernemq","port":"1883","clientid":"","usetls":false,"compatmode":false,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"26181dda.eabe72","type":"mqtt in","z":"e259d00c.c234f8","name":"","topic":"ia/factoryinsight/#","qos":"2","datatype":"auto","broker":"d81eab1a.cff018","x":380,"y":80,"wires":[["6f33d2f4.beb6fc"]]},{"id":"6f33d2f4.beb6fc","type":"debug","z":"e259d00c.c234f8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":610,"y":80,"wires":[]},{"id":"3fdff556.e4b17a","type":"inject","z":"e259d00c.c234f8","name":"","props":[{"p":"payload.begin_timestamp_ms","v":"","vt":"date"},{"p":"payload.aid","v":"","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":150,"y":140,"wires":[["5966dff5.e1f848","edbe929d.918a3"]]},{"id":"5966dff5.e1f848","type":"function","z":"e259d00c.c234f8","name":"addProduct ValveHead","func":"msg.payload = \n    {\n        \"product_id\": \"VH_Type123\",\n        \"time_per_unit_in_seconds\": 0.3\n    }\n\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"// to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":340,"y":140,"wires":[["be44677d.e204b8","79ff2b30.1eb9c4","1afbb195.172d76","6ed30fe6.d5c9d8"]]},{"id":"be44677d.e204b8","type":"mqtt out","z":"e259d00c.c234f8","name":"","topic":"ia/factoryinsight/TestLocation123/storage/addProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":820,"y":140,"wires":[]},{"id":"6d5ca5c1.9f1a44","type":"comment","z":"e259d00c.c234f8","name":"Info: Add the products","info":"Info: Testprocess like Assy1, station 2, without Gasket selection and without VH history (VH comes from Storage.)","x":160,"y":80,"wires":[]},{"id":"edbe929d.918a3","type":"function","z":"e259d00c.c234f8","name":"addProduct Gasket","func":"msg.payload = \n    {\n        \"product_id\": \"Gasket_Type123\",\n        \"time_per_unit_in_seconds\": 1.5\n    }\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"\n","finalize":"","x":350,"y":320,"wires":[["b6718fe8.1fe51","af45eab4.01f748","3562003.b91088","6ed30fe6.d5c9d8"]]},{"id":"79ff2b30.1eb9c4","type":"mqtt out","z":"e259d00c.c234f8","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/addProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":810,"y":200,"wires":[]},{"id":"1afbb195.172d76","type":"mqtt out","z":"e259d00c.c234f8","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1Gasket/addProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":840,"y":260,"wires":[]},{"id":"b6718fe8.1fe51","type":"mqtt out","z":"e259d00c.c234f8","name":"","topic":"ia/factoryinsight/TestLocation123/storage/addProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":820,"y":320,"wires":[]},{"id":"af45eab4.01f748","type":"mqtt out","z":"e259d00c.c234f8","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/addProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":810,"y":380,"wires":[]},{"id":"3562003.b91088","type":"mqtt out","z":"e259d00c.c234f8","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1Gasket/addProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":840,"y":440,"wires":[]},{"id":"6ed30fe6.d5c9d8","type":"debug","z":"e259d00c.c234f8","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":680,"y":580,"wires":[]},{"id":"19151a34.a343ae","type":"comment","z":"23ae98e1.65e538","name":"Info: Testprocess like Assy1 but without Gasket selection and without VH history (VH comes from Storage.)","info":"Info: Testprocess like Assy1, station 2, without Gasket selection and without VH history (VH comes from Storage.)","x":400,"y":440,"wires":[]},{"id":"86b91b56.b72fa8","type":"inject","z":"23ae98e1.65e538","name":"","props":[{"p":"payload.begin_timestamp_ms","v":"","vt":"date"},{"p":"payload.aid","v":"","vt":"num"}],"repeat":"130","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":130,"y":560,"wires":[["471760d9.1613f","c18519f1.c9b358"]]},{"id":"471760d9.1613f","type":"function","z":"23ae98e1.65e538","name":"New uniqueProduct from Storage","func":"msg.payload = \n    {\n      \"begin_timestamp_ms\": Date.now(),\n      \"end_timestamp_ms\": null,\n      \"productID\": \"VH_Type123\",\n      \"isScrap\": false,\n      \"uniqueProductAlternativeID\": String(flow.get(\"counterVH\"))\n    }\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"flow.set(\"counterVH\",57000458); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":360,"y":560,"wires":[["af7f8dee.974838","8601a0db.86ebf"]]},{"id":"af7f8dee.974838","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":670,"y":560,"wires":[]},{"id":"d500348d.1008b","type":"function","z":"23ae98e1.65e538","name":"New uniqueProduct from Assy1","func":"msg.payload = \n    {\n      \"begin_timestamp_ms\": Date.now(),\n      \"end_timestamp_ms\": null,\n      \"productID\": \"VH_Type123\",\n      \"isScrap\": false,\n      \"uniqueProductAlternativeID\": String(flow.get(\"counterVH\"))\n    }\n\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"// to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":350,"y":660,"wires":[["1e7fd6c2.969f19","c3b6d381.54ef08"]]},{"id":"1e7fd6c2.969f19","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":660,"wires":[]},{"id":"c18519f1.c9b358","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":660,"wires":[["d500348d.1008b","766745f0.493a44"]]},{"id":"c1ace356.4810f8","type":"function","z":"23ae98e1.65e538","name":"New addParentToChild from Assy1 for VH","func":"msg.payload = \n    {\n    \"timestamp_ms\": Date.now(),\n    \"childAID\": String(flow.get(\"counterVH\")),\n    \"parentAID\": String(flow.get(\"counterVH\"))\n    }\n\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"// to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":380,"y":760,"wires":[["8771cde7.513278","d1606de9.b4fef"]]},{"id":"8771cde7.513278","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":760,"wires":[]},{"id":"766745f0.493a44","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":760,"wires":[["c1ace356.4810f8","7bac099f.1f8b58"]]},{"id":"ec035d13.f5606","type":"function","z":"23ae98e1.65e538","name":"New productTag from Assy1","func":"msg.payload = \n{\n    \"timestamp_ms\": Date.now(),\n    \"AID\": String(flow.get(\"counterVH\")),\n    \"name\": \"torque1\",\n    \"value\": Math.random()+5\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"context.set(\"counter\",1000); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":340,"y":1580,"wires":[["6f373edf.3b1cc","ba70db66.fddf88"]]},{"id":"6f373edf.3b1cc","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1580,"wires":[]},{"id":"d30a795.5b6c008","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"4","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1580,"wires":[["ec035d13.f5606","1e7f6154.0fb39f"]]},{"id":"4eccf728.6043c8","type":"function","z":"23ae98e1.65e538","name":"New productTag from Assy1","func":"msg.payload = \n{\n    \"timestamp_ms\": Date.now(),\n    \"AID\": String(flow.get(\"counterVH\")),\n    \"name\": \"torque2\",\n    \"value\": Math.random()+5\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"context.set(\"counter\",1000); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":340,"y":1680,"wires":[["fa1c0df6.1280b8","7db849f5.9c6cc"]]},{"id":"fa1c0df6.1280b8","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1680,"wires":[]},{"id":"1e7f6154.0fb39f","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"4","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1680,"wires":[["4eccf728.6043c8","62c7ef7f.0b0cd8"]]},{"id":"2870f1d4.79a5b6","type":"function","z":"23ae98e1.65e538","name":"New productTag from Assy1","func":"msg.payload = \n{\n    \"timestamp_ms\": Date.now(),\n    \"AID\": String(flow.get(\"counterVH\")),\n    \"name\": \"torque3\",\n    \"value\": Math.random()+5\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"context.set(\"counter\",1000); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":340,"y":1780,"wires":[["92a0dc2b.d985f8","6a099aac.c0025c"]]},{"id":"92a0dc2b.d985f8","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1780,"wires":[]},{"id":"62c7ef7f.0b0cd8","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"4","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1780,"wires":[["2870f1d4.79a5b6","b39239ea.bd34f"]]},{"id":"bde7f942.51f72","type":"function","z":"23ae98e1.65e538","name":"New productTag from Assy1","func":"msg.payload = \n{\n    \"timestamp_ms\": Date.now(),\n    \"AID\": String(flow.get(\"counterVH\")),\n    \"name\": \"torque4\",\n    \"value\": Math.random()+5\n}\nflow.set(\"counterVH\", parseInt(msg.payload.AID) + 1); \n\nreturn msg;","outputs":1,"noerr":0,"initialize":"context.set(\"counter\",1000); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":340,"y":1880,"wires":[["1be93308.af06ed","1acd83d7.7423fc"]]},{"id":"1be93308.af06ed","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1880,"wires":[]},{"id":"b39239ea.bd34f","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"4","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1880,"wires":[["bde7f942.51f72"]]},{"id":"1acd83d7.7423fc","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/productTag","qos":"","retain":"","broker":"d81eab1a.cff018","x":790,"y":1920,"wires":[]},{"id":"6a099aac.c0025c","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/productTag","qos":"","retain":"","broker":"d81eab1a.cff018","x":790,"y":1820,"wires":[]},{"id":"7db849f5.9c6cc","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/productTag","qos":"","retain":"","broker":"d81eab1a.cff018","x":790,"y":1720,"wires":[]},{"id":"ba70db66.fddf88","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/productTag","qos":"","retain":"","broker":"d81eab1a.cff018","x":790,"y":1620,"wires":[]},{"id":"d1606de9.b4fef","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/addParentToChild","qos":"","retain":"","broker":"d81eab1a.cff018","x":810,"y":800,"wires":[]},{"id":"c3b6d381.54ef08","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/uniqueProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":800,"y":700,"wires":[]},{"id":"8601a0db.86ebf","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/storage/uniqueProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":810,"y":600,"wires":[]},{"id":"129636a.a30ccc9","type":"function","z":"23ae98e1.65e538","name":"New addParentToChild from Assy1Gasket for Gasket","func":"msg.payload = \n    {\n    \"timestamp_ms\": Date.now(),\n    \"childAID\": String(flow.get(\"counterGasket\")),\n    \"parentAID\": String(flow.get(\"counterGasket\"))\n    }\n\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"context.set(\"counter\",12000459); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":420,"y":1120,"wires":[["a57b69c.ef7cb98","e450a001.6daf"]]},{"id":"a57b69c.ef7cb98","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1120,"wires":[]},{"id":"3eb60608.f5d1e2","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1120,"wires":[["129636a.a30ccc9","2f2e5438.11093c"]]},{"id":"e450a001.6daf","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1Gasket/addParentToChild","qos":"","retain":"","broker":"d81eab1a.cff018","x":840,"y":1160,"wires":[]},{"id":"aa615c76.49656","type":"function","z":"23ae98e1.65e538","name":"New uniqueProduct Gasket from Storage","func":"msg.payload = \n    {\n      \"begin_timestamp_ms\": Date.now(),\n      \"end_timestamp_ms\": null,\n      \"productID\": \"Gasket_Type123\",\n      \"isScrap\": false,\n      \"uniqueProductAlternativeID\": String(flow.get(\"counterGasket\"))\n    }\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"flow.set(\"counterGasket\",12000459);  // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":380,"y":920,"wires":[["c2ff7c9a.83b4f8","56e976b3.7794"]]},{"id":"c2ff7c9a.83b4f8","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":920,"wires":[]},{"id":"56e976b3.7794","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/storage/uniqueProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":810,"y":960,"wires":[]},{"id":"44a0e9d5.f09c08","type":"function","z":"23ae98e1.65e538","name":"New uniqueProduct Gasket from Assy1Gasket","func":"msg.payload = \n    {\n      \"begin_timestamp_ms\": Date.now(),\n      \"end_timestamp_ms\": null,\n      \"productID\": \"Gasket_Type123\",\n      \"isScrap\": false,\n      \"uniqueProductAlternativeID\": String(flow.get(\"counterGasket\"))\n    }\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"// to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":400,"y":1020,"wires":[["47282209.9383c4","e6e4f35f.92d7c8"]]},{"id":"47282209.9383c4","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1020,"wires":[]},{"id":"e6e4f35f.92d7c8","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1Gasket/uniqueProduct","qos":"","retain":"","broker":"d81eab1a.cff018","x":830,"y":1060,"wires":[]},{"id":"9bda47ca.e639d","type":"function","z":"23ae98e1.65e538","name":"New productTag from Assy1Gasket for Gasket","func":"msg.payload = \n{\n    \"timestamp_ms\": Date.now(),\n    \"AID\": String(flow.get(\"counterGasket\")),\n    \"name\": \"ImageResolution\",\n    \"value\": 1080\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"context.set(\"counter\",1000); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":400,"y":1220,"wires":[["c22c900d.33d8e8","8370c69e.a46b7"]]},{"id":"c22c900d.33d8e8","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1220,"wires":[]},{"id":"2f2e5438.11093c","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"4","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1220,"wires":[["9bda47ca.e639d","e2c85ce7.7b5"]]},{"id":"8370c69e.a46b7","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1Gasket/productTag","qos":"","retain":"","broker":"d81eab1a.cff018","x":810,"y":1260,"wires":[]},{"id":"2d8283b8.564b7c","type":"function","z":"23ae98e1.65e538","name":"New addParentToChild from Assy1 for Gasket","func":"msg.payload = \n    {\n    \"timestamp_ms\": Date.now(),\n    \"childAID\": String(flow.get(\"counterVH\")),\n    \"parentAID\": String(flow.get(\"counterGasket\"))\n    }\nflow.set(\"counterGasket\", parseInt(msg.payload.parentAID) + 1); \n\nreturn msg;","outputs":1,"noerr":0,"initialize":"context.set(\"counter\",12000459); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":400,"y":1420,"wires":[["fb5152cb.a45ef8","9959f37c.cc7ec"]]},{"id":"fb5152cb.a45ef8","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1420,"wires":[]},{"id":"fa34ffcb.3c2cc8","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1420,"wires":[["2d8283b8.564b7c","d30a795.5b6c008"]]},{"id":"9959f37c.cc7ec","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1/addParentToChild","qos":"","retain":"","broker":"d81eab1a.cff018","x":810,"y":1460,"wires":[]},{"id":"7bac099f.1f8b58","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":920,"wires":[["26111f5c.a1e1f8","aa615c76.49656"]]},{"id":"26111f5c.a1e1f8","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1020,"wires":[["3eb60608.f5d1e2","44a0e9d5.f09c08"]]},{"id":"7a196298.eb854c","type":"comment","z":"23ae98e1.65e538","name":"VH scanned","info":"Info: Testprocess like Assy1, station 2, without Gasket selection and without VH history (VH comes from Storage.)","x":350,"y":500,"wires":[]},{"id":"9a1b9082.6f2828","type":"comment","z":"23ae98e1.65e538","name":"Good Gasket scanned","info":"Info: Testprocess like Assy1, station 2, without Gasket selection and without VH history (VH comes from Storage.)","x":400,"y":860,"wires":[]},{"id":"86081562.0e862","type":"comment","z":"23ae98e1.65e538","name":"Screwing","info":"Info: Testprocess like Assy1, station 2, without Gasket selection and without VH history (VH comes from Storage.)","x":360,"y":1520,"wires":[]},{"id":"ace5904a.d89a28","type":"mqtt out","z":"23ae98e1.65e538","name":"","topic":"ia/factoryinsight/TestLocation123/Assy1Gasket/productTagString","qos":"","retain":"","broker":"d81eab1a.cff018","x":830,"y":1360,"wires":[]},{"id":"5928a7bc.4c059","type":"debug","z":"23ae98e1.65e538","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":1320,"wires":[]},{"id":"81caa86.0b676d8","type":"function","z":"23ae98e1.65e538","name":"New productTagString from Assy1Gasket for Gasket","func":"msg.payload = \n{\n    \"timestamp_ms\": Date.now(),\n    \"AID\": String(flow.get(\"counterGasket\")),\n    \"name\": \"precision\",\n    \"value\": \"high\"\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"context.set(\"counter\",1000); // to store a variable/ Code added here will be run once\n// whenever the node is started.\n","finalize":"","x":420,"y":1320,"wires":[["5928a7bc.4c059","ace5904a.d89a28"]]},{"id":"e2c85ce7.7b5","type":"delay","z":"23ae98e1.65e538","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":1320,"wires":[["81caa86.0b676d8","fa34ffcb.3c2cc8"]]}]

**Comment by Scarjit** [comment]
We now have multiple simulators integrated into the stack
