### ISSUE TITLE
Problem with queue: locking

### ISSUE THREAD

**Issue by larswitte** [united-manufacturing-hub/united-manufacturing-hub#500]
**Problem Description**
The specific problem occured after a product wasn't addet to the productTable. Follwing uniqueProduct MQTT messages couldn't be processed. Because of that also addParentToChild and productTag messages were not processed.

Deleting the mqtt-to-postgres pod and adding the missing product to the productTable didn't solve the issue: still no new uniqueProducts, productTags and addParentToChild messages were processed.

**Suspected underlying issues:**
1. If one queue item has an issue writing into sql, everything is put back into the queue and retried from the beginning (even queue items that are already in the timescaleDB)
2. After one issue, mqtt-to-postgres doesn't try to write the following queue items into timescaleDB but breaks. Because of that, certain queue items (previous items might depend on) are never even tried to write in queue.
3. After a while there are no error messages any more witch might be, because `stmt.Close()` isn't executed in case of errors.

*Example*
Message 1: -> wrote into DB
Message 2: depends on Message 3 -> issue, process stopped
Message 3: -> never tried to write in db

[repeat]

**Possible solution**
1. Try to write every message into db, only put not working messages back into queue
2. Close with `stmt.Close()`, even in case of errors
3. to prevent the queue from gradually filling with problematic messages, add timeout for queue items (maybe long term store somewere else)

*Example*
Message 1: -> wrote into DB
Message 2: depends on Message 3 -> issue, returned and put back into queue the next time
Message 3: -> wrote into DB

Message 2: retried -> wrote into DB (because now Message 3 is already in DB)

**Comment by Scarjit** [comment]
Fixed in #506
