### ISSUE TITLE
Add "Datalogic S.r.I and its affiliates Magellan 1500i" to list of known Barcode Scanners

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#511]

**Comment by JeremyTheocharis** [comment]
Can you elaborate what you mean here?

**Comment by kruegeralex** [comment]
@Scarjit in the enviroment variables for the barcodescanner microservice barcodescanner can be specified if i am correct. I want this barcodescanner to the list

**Comment by Scarjit** [comment]
Not relevant in newer version
