### ISSUE TITLE
Overwrite data via MQTT (mqtt-to-postgresql)

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#52]
In order to implement the higher-level EPIC, the following data must be able to be changed via MQTT in this work package:

- machine states (states), 
- shifts, 
- produced pieces (count) (may require extension for scrap)

**Comment by Scarjit** [comment]
This needs more information:

**Shifts:**
mqtt-to-postgres already allows modification of shifts, [by sending the same begin_timestamp & asset id](https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/main/golang/cmd/mqtt-to-postgresql/database.go#L1095).

Should there be another mqtt command, to only update, but not insert data ?
