### ISSUE TITLE
Add to documentation which processValues are ignored

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#525]
Sometimes processValues are ignored (e.g., the ones called `measurement`). This is for legacy reasons. We should document them.

https://github.com/Scarjit/united-manufacturing-hub/blob/7830e9d03a7733782125e8ba879c0e4899537342/golang/cmd/mqtt-to-postgresql/processValueData.go#L207-L210

**Comment by Scarjit** [comment]
mqtt-to-postgresql is deprecated.
kafka-to-postgresql's processValue isn't ignoring any messages
