### ISSUE TITLE
MQTT-to-postgres can still lock up

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#527]
I went through the digital shadow functionalities and they seemed to be very stable regarding speed of the scanning.

When I send the `addProduct` Messages to fill the `productTable` before I send `uniqueProduct` and `addParentToChild` messages I can still intentionally produce locking. 
I interestingly couldn't produce locking if i send `addParentToChild` messages before sending the `uniqueProduct` messages, but the number of messages was lower.

Roughly tested and normally really well working:
- addParentToChild
- uniqueProduct
- productTag
- productTagString
- processValue
- processValueString

I didn't test the rest.

_Originally posted by @larswitte in https://github.com/united-manufacturing-hub/united-manufacturing-hub/issues/506#issuecomment-916236133_

**Comment by larswitte** [comment]
Here is how you can replicate it:
1. Run `IntegrationTest2: ExampleStation` for one time
2. Try Running `IntegrationTest1: AddProducts`.

At that point it's already locked up I think. At least datagrip doesn't show any products added in the `productTable`.


@kruegeralex found a solution to fix it by deleting the persistant volume of mqtt-to-postgresql. After that product could be added again, and the rest also seemed to work.
