### ISSUE TITLE
Git guardian API key missing

### ISSUE THREAD

**Issue by Gornoka** [united-manufacturing-hub/united-manufacturing-hub#543]
## Expected Behavior

Git guardian doing its checks 

## Current Behavior

Git guardian crashing through missing API key.

See #542 for example

**Comment by JeremyTheocharis** [comment]
The reason for this is that you are an external and therefore have no access to the API key (compared to write access to this repo). I can check what is possible here.

**Comment by Gornoka** [comment]
thanks for the explanation
