### ISSUE TITLE
Digital shadow server problem

### ISSUE THREAD

**Issue by larswitte** [united-manufacturing-hub/united-manufacturing-hub#544]
**Problem Description**
To fix queue locking it tried removing the mqtt-to-postgresql pod and the mqtt-to-postgresql statefulset (should have removed the statefulset, instead of the persistent volume).
After that, neither the mqtt-to-postgresql pod nor the statefulset reappeared in lens. At that point we rolled back the server.
Then the mqtt-to-postgresql pod and persistent volume came back again, but factorycube-server-grafana had an error with the grafana datasource.

Now, approximately 15 minutes later, grafana is running again and I can log in, but there are no grafana dashboards loaded as far as I can tell.

How should I proceed?

**Comment by JeremyTheocharis** [comment]
Cause:
not digital shadow, but the previous update from 0.3.2 to 0.6.0. DUring that update we changed the Grafana datasource from ia-datasource to umh-datasource, which was not reflected in the values.

Solution:
Copy the umh-datasource parts from the 0.6.0 version and overwrite with it the configurations that were still on the server from the version 0.3.2.
