### ISSUE TITLE
factory cube edge and server can not run on the same device reliably since they both occupy the same port for mqtt

### ISSUE THREAD

**Issue by Gornoka** [united-manufacturing-hub/united-manufacturing-hub#547]
when running factory cube edge and server on the same device both mqtt brokers try to use the same port, this yields unpredictable behaviour since one broker may be faster than the other
## Expected Behavior

Tell us what should happen 
both brokers should use different porst so that factorycube edge and server can run on the same device/ network adapter
## Current Behavior

they both bind on the same port and one randomly crashes 
## Possible Solution

change one to use a different port (probably server since edge has more connections to external software)

## Steps to Reproduce
1. install factorycube edge and server using the install guide ( development config)
2. observe unpredictable behaviour

**Comment by Gornoka** [comment]
issue is depending on the exact hardware this runs on.
quick fix from @JeremyTheocharis delete factorycube-server-vernemq service

**Comment by Scarjit** [comment]
Fixed with 0.8.X
