### ISSUE TITLE
docs: find new minikube tutorial link

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#561]
Do we really want to link the german documentation, inside an english "Getting started" guide ?

_Originally posted by @Scarjit in https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/554#discussion_r714769108_

The english link does not work, therefore, we have to use the German version for now. However, we should find a new link.

**Comment by Scarjit** [comment]
Kubernetes Minikube installation guide (https://kubernetes.io/docs/tasks/tools/) redirects to Minikubes own site (https://minikube.sigs.k8s.io/docs/start/)
