### ISSUE TITLE
Manually working with umh-datasource is not possible due to "API key not configured"

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#575]
Manually working with umh-datasource is not possible due to "API key not configured"

## Expected Behavior

Manually adding the datasource should be possible.

## Current Behavior

Currently there is the error message "API key not configured" when trying to save.

## Possible Solution

Probably the variable "apiKeyConfigured" is not set when using the UI of Grafana.

**Comment by Scarjit** [comment]
Is this still an issue ?
