### ISSUE TITLE
All HTTP API's must be Openapi compatible

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#628]
**Is your feature request related to a problem? Please describe.**
Our current HTTP API is sometimes not according to best practices.

**Describe the solution you'd like**
Any microservice, which exposes an HTTP API must also have an matching OpenAPI 3 specification.

- [x] #644
- [x] #645
- [x] #646
- [x] #647
- [ ] #643
- [ ] #86 
- [ ] #87 
- [ ] #85 
- [ ] #88 
- [ ] #89 
- [ ] #90 
- [ ] #91 
- [x] #92 
- [ ] #93

**Comment by JeremyTheocharis** [comment]
see also https://github.com/united-manufacturing-hub/united-manufacturing-hub/milestone/7
