### ISSUE TITLE
configmap "kube-root-ca.crt" not found

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#641]
When starting up mqtt-to-blob the error message appears `configmap "kube-root-ca.crt" not found`. This is caused by using a k8s version before v1.20.0 (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#introducing-rootcaconfigmap)

## Expected Behavior

The user should be warned during the installation that mqtt-to-blob will not work.

## Current Behavior

Nothing happens

## Possible Solution

Upgrade to a higher kubernetes version. Add a warning message during installation that mqtt-to-blob will not work (as the latest message after `this might take a while` so its visible to unexperienced users)

Output of `k3s -v`
```
development [~]$ k3s -v
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8
```

**Comment by Scarjit** [comment]
Fixed in https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/631/commits/24f3e0403e38bfb8c9bb1fa62567146a1e7f47a6
