### ISSUE TITLE
Create openapi specification for factoryinsight and add "v1.0.0 preview" to the documentation

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#644]
**Is your feature request related to a problem? Please describe.**
It is unclear how the API will look like in v1.0.0

**Describe the solution you'd like**
We should document our target state for the v1.0.0 architecture in the documentation as soon as possible, so that other applications can build on top of that and that we have a shared goal.

For this we need to align on the openapi specification first

**Comment by Scarjit** [comment]
Superseded by https://github.com/united-manufacturing-hub/united-manufacturing-hub/issues/1385
