### ISSUE TITLE
Implement "v1.0.0 preview" openapi specification into factoryinsight

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#645]
**Is your feature request related to a problem? Please describe.**
Only having the v1.0.0 preview as stated in #644 is not helpful.

**Describe the solution you'd like**
We need to implement it as well.

**Comment by Scarjit** [comment]
Superseded by https://github.com/united-manufacturing-hub/united-manufacturing-hub/issues/1385
