### ISSUE TITLE
Create new database model using DDL "v1.0.0 preview" and upload to documentation

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#648]
See also comments in #367

**Comment by Scarjit** [comment]
Tracking in branch [648-new-database-definition](https://github.com/united-manufacturing-hub/united-manufacturing-hub/tree/648-new-database-definition).

**Comment by JeremyTheocharis** [comment]
let's not forget it to change it [here](https://docs.umh.app/docs/concepts/mqtt/#timescaledb-structure) as well

**Comment by Scarjit** [comment]
Superseded by https://github.com/united-manufacturing-hub/united-manufacturing-hub/issues/1280
