### ISSUE TITLE
Enable customizable queries / BI integration

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#659]
**Is your feature request related to a problem? Please describe.**
A customer might have varying needs for the KPIs, e.g., only show the temperature when machine was not running.

**Describe the solution you'd like**
The user can specify queries when communicating with factoryinsight.

**Describe alternatives you've considered**
A good alternative would be replicating the REST API into a relational database for consumption of a BI tool.
Maybe even include GraphQL?

**Additional context**
Based on expert discussions

**Comment by Scarjit** [comment]
Is this still relevant @JeremyTheocharis  ?
