### ISSUE TITLE
Long time between MQTT message and readable message in dashboard (>30 seconds)

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#660]
For an impressive impression, the time between the arrival of a message and its display in the dashboard should be <<5 sec

Please contact @kruegeralex  to get access to the test environment.

**Comment by JeremyTheocharis** [comment]
Could you describe further what is happening? Used versions? CPU load? (Previous release had high CPU usage, probably system was not upgraded yet)

**Comment by kruegeralex** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/77407527/142256368-97cc6b93-8728-4753-9d05-c0393045a9b6.png">

Helm chart version 0.6.0 with mqtt-to-postgres upgraded to 0.7.0 @Scarjit correct me if i am wrong

**Comment by Scarjit** [comment]
I assume the messages get stuck due to a large amount of invalid messages.
The solution will be to tweak the sleep times, but this will also increase CPU load, due to the increased amount of times it tries & failes to insert incorrect data.

**Comment by Scarjit** [comment]
See #671
