### ISSUE TITLE
MQTT Bridge fails to build up connection 

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#661]
Please contact @kruegeralex to get access to the test environment
[factorycube-edge-mqttbridge-0.log](https://github.com/united-manufacturing-hub/united-manufacturing-hub/files/7520665/factorycube-edge-mqttbridge-0.log)
t.

**Comment by JeremyTheocharis** [comment]
This issue is likely caused by a LevelDB corruption. Delete the PersistentVolume of mqtt-bridge.

This issue is already known. Will link to the other once I am back from holidays.

**Comment by kruegeralex** [comment]
How do i delete the persistent Volume? 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/77407527/142413260-b80e8303-6d90-41f3-9f63-4881715e3ac3.png">

With the procedure described in the picture, the persistent volume disappears from the list for a short time, but then reappears with an age of 154 days.

**Comment by JeremyTheocharis** [comment]
I'll write a guide answering this question

**Comment by Scarjit** [comment]
MQTTBridge is no longer part of the active stack
