### ISSUE TITLE
Add Favicon to Documentation

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#668]
<img width="88" alt="image" src="https://user-images.githubusercontent.com/77407527/142412814-fef11456-2472-41f8-b84d-6331f140578a.png">

**Comment by Scarjit** [comment]
@kruegeralex Can you provide the icon file, you wish to have displayed ?

**Comment by kruegeralex** [comment]
@chrisproch can you provice @Scarjit with the favicon from the website?

**Comment by kruegeralex** [comment]
![Favicon](https://user-images.githubusercontent.com/77407527/143062635-1ea100dd-6f86-4361-9469-d7fa0881d4e4.png)
![Favicon_67X67](https://user-images.githubusercontent.com/77407527/143062639-1de4d755-5145-48f7-aa96-6e61b0d451ba.png)
