### ISSUE TITLE
Create FAQ with most common questions in Industrial IoT

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#669]
Anwering questions like:

- •	cost and implementation timeline for retrofitting?
- •	wireless sensors vs. wired sensors, why not using wireless?
- •	which standards / protocols (e.g. OPC UA?) are recommended in terms of interoperability?
- •	on premises vs. cloud vs. edge?
- •	importance of scalability for production: number of machines (scalability in terms of data point of view and machine-machine communication) vs. number of people (not so important)?
- •	how many industries are using MQTT and NodeRED?
- •	influxDB vs. time scale DB? why using time scale DB?
- •	trade-off use cases <> infrastructure: designing use cases <> collecting a lot of data… combination: think about important key use cases and data points and build architecture upfront, think about layout before full implementation

**Comment by Scarjit** [comment]
This should not be part of this repo
