### ISSUE TITLE
Add MQTT-Kafka bridge

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#670]
**Describe the solution you'd like**
Since external solutions still rely on MQTT, we need an bridge to convert MQTT Messages <-> Kafka Events.

This bridge could be a Kafka plugin or an seperate microservice

**Comment by JeremyTheocharis** [comment]
It might also make sense to communicate between distant kafka brokers (one the factory, one in the cloud somewhere) via MQTT because one does not want to share all data between factory and the cloud. No fixed opinion here, just throwing it into the idea bucket.

**Comment by Scarjit** [comment]
> It might also make sense to communicate between distant kafka brokers (one the factory, one in the cloud somewhere) via MQTT because one does not want to share all data between factory and the cloud. No fixed opinion here, just throwing it into the idea bucket.

This should be possible by setting it up like this:

Stack 1 [Internal communication in Kafka] -> [MQTT-Kafka-Bridge] -> Some MQTT Broker (ex: In azure or on premise at stack 1 / 2) -> [MQTT-Kafka-Bridge] -> Stack 2 [Internal communication in Kafka]

**Comment by Scarjit** [comment]
We might want to have some kind of config to control which MQTT/Kafka messages will be bridged.

**Comment by Scarjit** [comment]
Blocked by #674
