### ISSUE TITLE
Write guide to delete data in Kubernetes cluster

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#672]
Related to https://github.com/united-manufacturing-hub/united-manufacturing-hub/issues/661

Sometimes it is necessary to delete data in the Kubernetes cluster. Unfortunately, this is not easy and might result in the persistent volumes not beeing recreated, etc.

**Comment by Scarjit** [comment]
Is this still relevant @JeremyTheocharis  ?
