### ISSUE TITLE
Remove landingpage from documentation

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#680]
When you currently go to docs.umh.app, you are greeted by a "start page", which currently adds no value, so I suggest removing it.

**Comment by Scarjit** [comment]
@kruegeralex Please comment, whether this issue is still relevant (after discussion with @chrisproch)

**Comment by chrisproch** [comment]
> @kruegeralex Please comment, whether this issue is still relevant (after discussion with @chrisproch)

Can be removed.
