### ISSUE TITLE
Document Kafka <--> MQTT in architecture

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#692]
**Is your feature request related to a problem? Please describe.**
Components that are not documented will confuse people

**Describe the solution you'd like**
If we enable Kafka by default, we need to document it in the architecture as well: https://docs.umh.app/docs/concepts/

**Comment by JeremyTheocharis** [comment]
Still open, see also https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/810#issuecomment-1022170707

**Comment by Scarjit** [comment]
@JeremyTheocharis Should this stay open ?

**Comment by Scarjit** [comment]
@JeremyTheocharis Should this stay open ?
