### ISSUE TITLE
Add instruction to change ip-range 

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#717]
As described in Issue #703, the information on how to set the Ip range is missing in the setup.

This leads to the user thinking that the programme does not work. I suggest expanding the instructions accordingly with illustrated instructions.

**Comment by oarne97** [comment]
@JeremyTheocharis  any update on this. It blocks #455

**Comment by oarne97** [comment]
@JeremyTheocharis 
![image](https://user-images.githubusercontent.com/92309208/146157828-96a97b5f-0f11-4fcc-b659-f7d99dfe7f77.png)

Thats the second option but I get this error..

Also: Can you shortly explain how i can adapt the ip range in the development file?

**Comment by JeremyTheocharis** [comment]
1. [Related to your error message](https://docs.umh.app/docs/tutorials/united-manufacturing-hub/working-with-helm-and-lens/#release-factorycube-edge-or-factorycube-server-not-found-when-updating-the-helm-chart). We should add there an tutorial on how to install Helm on Windows (suggestion: [using choco](https://www.studytonight.com/post/installing-kubernetes-helm-on-windows)). Additionally, we should link to the article mentioned above as this will happen to everyone when first using the system. See also #767 
2. You can change the development file by downloading it, changing it and then hosting it yourself --> #768
