### ISSUE TITLE
Combine various datamodel related articles in documentation into one chapter

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#718]
**Is your feature request related to a problem? Please describe.**
Currently, there are various places where the datamodel is scattered:
1. https://docs.umh.app/docs/concepts/mqtt/
2. https://docs.umh.app/docs/concepts/state/
3. https://docs.umh.app/docs/concepts/digitalshadow/
4. https://docs.umh.app/docs/developers/factorycube-server/factoryinsight/
5. https://docs.umh.app/docs/developers/factorycube-server/factoryinput/
6. see also changes in #715 

**Describe the solution you'd like**
We should have only one chapter in the documentation guiding the reader through it. Suggestion:

/concepts/datamodel --> Give introduction
/concepts/datamodel/mqtt --> Explaining MQTT messages
/concepts/datamodel/database --> explaining database model (see #715). not for current datamodel (not worth it, let's just do that for the preview)
/concepts/datamodel/rest-api --> explaining factoryinsight and factoryinput
/concepts/datamodel/application-digital-shadow --> explaining how to use the datamodel to work with digital shadow
/concepts/datamodel/application-oee --> explaining how to use the datamodel to work with OEE (not worth it, let's just do that for the preview)

Furthermore, we should do the same for /concepts/datamodel-preview to fulfil #648 #645 #646 #652

**Comment by Scarjit** [comment]
superseded by learn
