### ISSUE TITLE
Extension of factoryinsight for time series TARGET vs ACTUAL production

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#731]
In many production facilities, the currently used and desired diagram is a time series that compares the TARGET with the ACTUAL production.

See figure:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/77407527/144072689-8c0326d3-3bf9-44aa-b157-79515e247228.png">

As a user of the United Manufacturing Hubs, I would also like to be able to use this visualisation.

To do this, I only want to tell the system the current products produced via an MQTT topic ("/count"?) and in some way also the target speed.
It would also be interesting to be able to set up the chart so that the target speed is extrapolated and, if necessary, the sum of the target production for this shift is displayed in the same chart. 

This feature was requested by a partner company.

**Comment by kruegeralex** [comment]
@JeremyTheocharis , @Scarjit any idea how much work would be involved to integrate this solution?

**Comment by Scarjit** [comment]
That should be doable.
orderTable already has the target_units for a time range.
productTable has time_per_unit_in_seconds.

**Comment by Scarjit** [comment]
@kruegeralex Is this what you are looking for:

![image](https://user-images.githubusercontent.com/6317420/148751143-bc5a8a39-66f7-4184-a8b1-fcee4ecafe8c.png)

This would allow to extract the produced items per order, scrapped items, target items (as defined at order creation), and the maximum producible in this timeframe (product table has time per unit)

**Comment by Scarjit** [comment]
Implementing this for a shift instead of a single order would also be easily possible, by getting all orders inside the shift first

**Comment by kruegeralex** [comment]
![image](https://user-images.githubusercontent.com/77407527/148768886-09bd61c8-d0e2-497a-a8aa-da1aad976586.png)

**Comment by kruegeralex** [comment]
![image](https://user-images.githubusercontent.com/77407527/148786324-b7d9db4b-32a9-4558-9923-64dfc665c88d.png)

**Comment by kruegeralex** [comment]
Here an idea for a test set: 
![image](https://user-images.githubusercontent.com/77407527/149140261-19b06edb-18eb-4300-8999-95a709ea9af1.png)

**Comment by kruegeralex** [comment]
![image](https://user-images.githubusercontent.com/77407527/149334298-f5ba3bed-fb2e-4fc6-b37a-1f8664777fcd.png)
