### ISSUE TITLE
mqtt-kafka-bridge: show error message that the content is not a valid json

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#738]
mqtt-kafka-bridge error message should be modified so that it gets clear that the cause is a non valid json. Currently it shows only INVALID. Better: Warning: message not forwarded because the content is not a valid JSON.

**Comment by Scarjit** [comment]
@JeremyTheocharis Can you give me an sample, of valid json, that mqtt-kafka-bridge will not accept ?

**Comment by JeremyTheocharis** [comment]
Updated the issue with a better explaination

**Comment by Scarjit** [comment]
Thanks, ill give it a look later today.
