### ISSUE TITLE
Add logic: remove message from log once processed from all consumer groups

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#743]
Otherwise the message will stay forever. Main challenge: What happens if there are multiple consumer groups? We need to ennsure that all consumer groups have processed the message before deleting it. 

We could use an expiration, e.g., on the overall amount of data in the buffer. https://kafka.apache.org/documentation/#retention.bytes
https://kafka.apache.org/documentation/#retention.ms

**Comment by Scarjit** [comment]
According to the Kafka docs, the default retention.ms is 7 days.

If we really want to make sure, that everybody has processed the message, we would need another database to track the processing progress of each microservice.
Alternatively we could just assume that microservices, that take more then 7 days to process the message are not in service anymore.

**Comment by JeremyTheocharis** [comment]
Maybe do a rough calculation in which scenarios 7 days will be too much (e.g., sending 5000 messages per second might result in unnecessary large storage capacity)

**Comment by Scarjit** [comment]
We can add an storage limit, but that would need documentation. (e.g: about the risk of setting the value to low)

**Comment by JeremyTheocharis** [comment]
We need to document it either way. Maybe let's leave it as it is currently
