### ISSUE TITLE
Dashboard for tool wear

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#755]
As a user, I would like to have a dashboard that gives me at a glance relevant KPIs to the machine such as:

- Output quantity
- Remaining tool life in percent
- Next exchange in X hours
- A graph about the degree of utilization

@JeremyTheocharis what do you think how many adjustments should be made in the backend to describe the asset machine like this?

**Comment by JeremyTheocharis** [comment]
As discussed: my estimate for a stable solution here is 3 months FTE (together with features to change data in the dashboard).

**Comment by Scarjit** [comment]
Is this still relevant @JeremyTheocharis  ?
