### ISSUE TITLE
Add tutorial on how to install Helm on Windows

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#767]
**Is your feature request related to a problem? Please describe.**
The current guide requires having Helm installed, see #717 

**Describe the solution you'd like**
We should explain how to install Helm on Windows, e.g., using choco and include it in the guide

**Comment by Scarjit** [comment]
https://learn.umh.app/guides/getstarted/installation/local-k3d-installation/
