### ISSUE TITLE
Bug Report: first 12 addProduct messages do not work

### ISSUE THREAD

**Issue by onurcankaraman** [united-manufacturing-hub/united-manufacturing-hub#771]
### Expected Behavior

When sending a addProduct MQTT message it should be stored in the database

### Current Behavior

The first 12 messages are not stored, probably because the internal database id starts with 1 and there are already 12 elements in the database

### Steps to Reproduce

Install stack
Send 13 messages of addProduct
Only the last message will be stored

### Context (Environment)

Working with the development setup

### Version

v0.7.x

**Comment by JeremyTheocharis** [comment]
@Scarjit let's combine it with your current database rework

**Comment by Scarjit** [comment]
Reproduced on a fresh database
