### ISSUE TITLE
Convert states to string when keepStatesInteger is false and aggregationType is 1

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#84]
Convert states to string when keepStatesInteger is false and aggregationType is 1

## Expected Behavior

If keepStatesInteger is set to false or not set (default value is false) the returned states should be in string format. 

## Current Behavior

If aggregationType is 1 the returned values are always in integer.

## Steps to Reproduce

`https://api.app.industrial-analytics.net/api/v1/DCCAachen/Aachen/warping/aggregatedStates?from=2020-06-18T17:07:22Z&to=2021-07-13T21:11:27Z&includeRunning=False&aggregationType=1`

This returns:

```json
{
    "columnNames": [
        "category",
        "state",
        "duration"
    ],
    "datapoints": [
        [
            9,
            150000,
            3638.4260000000004
        ],
        [
            9,
            160000,
            2001.471
        ],
        [
            10,
            150000,
            6185.870000000001
        ],
        ....
    ]
}```

**Comment by Scarjit** [comment]
this is resolved in v2 frontend
