### ISSUE TITLE
Our stack should have scripts for easier setup and configuration

### ISSUE THREAD

**Issue by Scarjit** [united-manufacturing-hub/united-manufacturing-hub#843]
**Is your feature request related to a problem? Please describe.**
 1) Our current workflow has private keys in .yaml files, which easily get uploaded to public sites. 
 2) Lens is not always the most comfortable way to manage our stacks settings.

**Describe the solution you'd like**
We should create scripts to easily change kubernetes configuration parameters. (e.g. en/disable services, change service settings, ...)
We also should create a script to download the required private keys, so we don't have to put them in .yaml files anymore.

**Describe alternatives you've considered**
We could manage the certs with kubernetes.
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

**Comment by JeremyTheocharis** [comment]
Currently working on a commercial plugin to help with that. Not scope for open source
