### ISSUE TITLE
MQTT Broker does not respond

### ISSUE THREAD

**Issue by onurcankaraman** [united-manufacturing-hub/united-manufacturing-hub#853]
### Expected Behavior

In the updated version of umh, MQTT Broker should stay in "connected" status on the nodered screen. So  the data should be sent to Grafana via nodered. It should be also possible to connect to MQTT Broker via MQTT explorer and i should see the data flow on explorer. 

### Current Behavior

In the updated version of umh, MQTT Broker stays in "connecting" status on the nodered screen. So ı can not send data to Grafana via nodered. MQTT Broker appears in running status on Lens. When I want to connect to MQTT Broker via MQTT explorer nothing appears on screen. 

**_Images_**

![image](https://user-images.githubusercontent.com/47088037/153603056-2aa65e3b-bd6f-49cb-b1ae-c9bcea2ad505.png)
![image](https://user-images.githubusercontent.com/47088037/153603096-e0395dca-c838-4253-a141-66003b1c7ed9.png)
![image](https://user-images.githubusercontent.com/47088037/153603106-7f574d98-2a8c-43fe-a5f8-76a4ac885bb6.png)

### Steps to Reproduce

1. Complate Installation.
2. Connect Lens, Grafana and NodeRed
3. Try Connect MQTT Broker

### Context (Environment)

Installed k3os via default development.yaml on IPC. Installations completed succesful but no data can be send to grafana via nodered. 

### Version

not applicable

**Comment by JeremyTheocharis** [comment]
Which username and topic are you using in MQTT broker? it should be username `ia_nodered` and topic `ia/#`

**Comment by onurcankaraman** [comment]
It should be whatever is assigned as the default value, I did not make any manual changes. But if you tell me where to check, I can check and get back to you immediately.

By the way, I noticed something while I was playing around, but still no solution. When I'm tampering with the MQTT Output node in Node Red, if I update the protocol to MQTT V3.1(Legacy), I only see the text "Connection Established" on nodered. But when I send data, no data goes to grafana. At the same time, I cannot see the data flow through MQTT Broker.

**IMAGES**
![image](https://user-images.githubusercontent.com/47088037/154017662-93647bee-b3ab-47cc-855f-b9419596e216.png)
![image](https://user-images.githubusercontent.com/47088037/154017729-485750ee-cddf-4768-89c3-94496486ed7a.png)

**Comment by Scarjit** [comment]
Please goto the security tab and use the values provided above by @JeremyTheocharis

**Comment by JeremyTheocharis** [comment]
![image](https://user-images.githubusercontent.com/30755722/154185962-db50fd42-5123-40d6-a340-ad64b4934282.png)
This security tab :)

**Comment by onurcankaraman** [comment]
When I entered the user name, the data flow started. I can see the data in Grafana but not on MQTT Explorer.

![image](https://user-images.githubusercontent.com/47088037/154431522-252e8f9f-f922-4a86-a693-8a571f44bb64.png)

**Comment by Scarjit** [comment]
@onurcankaraman Which Username and MQTT Client ID have you set in MQTT Explorer ?

**Comment by onurcankaraman** [comment]
I don't know. When I loaded the vernemq certificates from Lens software to mqtt explorer (I saved all of them in a notepad and selected them one by one from the advanced menu), the problem was solved.
![image](https://user-images.githubusercontent.com/47088037/154439855-41ec2c19-08fa-4491-b656-f744fe720377.png)

**Comment by onurcankaraman** [comment]
I am having the same issue again with MQTT Explorer. Even though I installed the certificates, the data does not appear here. There is data flow between NodeRed and Grafana. It just doesn't show up here.

![image](https://user-images.githubusercontent.com/47088037/155509604-5d1add18-d3d7-46a5-9709-41065931d436.png)
![image](https://user-images.githubusercontent.com/47088037/155509640-26f3d3a7-177d-4dea-bfad-5bd753d27ef6.png)
![image](https://user-images.githubusercontent.com/47088037/155509668-b82e7907-9dfd-4c3a-98ed-7cde2ef324b5.png)

**Comment by Scarjit** [comment]
@onurcankaraman Is there any difference between what you have tried today, and what worked in your last post ?

**Comment by onurcankaraman** [comment]
I didn't do anything different. I see Connected, but I can't see the data stream.

Today, when I want to send data to a different location and assets, I noticed that location and asset do not occur. Data flow is done only for test location and asset.

**Comment by JeremyTheocharis** [comment]
You need to subscribe to the topic `ia/#` and not `#` as there is an ACL thats forbidding you from subscribing everything

**Comment by onurcankaraman** [comment]
I'm using ia/# as a topic, but it doesn't change anything. (In the last case, I could see the data flow when I did this).
![image](https://user-images.githubusercontent.com/47088037/155664398-ccbc0228-6329-432b-86e6-4cc34ed21699.png)

However, I restarted the pods with the thought, "Is there a problem with the pods?" and I encountered this error. I can't run any code right now.

![image](https://user-images.githubusercontent.com/47088037/155664359-98925531-45b7-4007-be37-8767bf98ce17.png)

I think you mentioned this in bug #837 but it is marked as resolved. How can I get this update?

**Comment by Scarjit** [comment]
@onurcankaraman What version is your stack on ?

**Comment by onurcankaraman** [comment]
0.8.0, if I'm looking in the right place  😄 
![image](https://user-images.githubusercontent.com/47088037/155684070-1c238265-eea4-485d-b2c7-92716ac124d7.png)

**Comment by Scarjit** [comment]
Hm,

[auto plugin installation](https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/24776c3fc67e0581b107081127edf77291dc820d/deployment/united-manufacturing-hub/templates/nodered-statefulset.yaml#L46-L57) was tested in 0.8.0, you can still manually install them by opening the [Palette Manager](https://nodered.org/docs/user-guide/editor/palette/manager) and installing:
```
node-red-contrib-modbus
node-red-contrib-edge-trigger
node-red-contrib-opcua
node-red-contrib-s7
node-red-contrib-cron-plus
```

Is you stack a fresh install, or have you migrated from 0.7.X ?

**Comment by onurcankaraman** [comment]
I did a clean install. I did not update. Depending on the situation, I will try the 0.8.x version on the virtual machine and continue with the 0.7.x version on the IPC. (For progress in the project. We can switch to 0.8.x again in the following stages.).

I'm trying to install manually.

**Comment by JeremyTheocharis** [comment]
If the issue persists we could jump on a video call with you as we are interested in how you got to that point and solving it will be probably easier.
