### ISSUE TITLE
Bug Report: server certificate when accessing IPs

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#865]
### Expected Behavior

When using the normal PKI guide and using an IP instead of DNS, it should still work

### Current Behavior

It does not work, because 
```
X509v3 Subject Alternative Name:
IP Address:172.20.22.10
```

is not set

### Steps to Reproduce

Follow PKI guide

### Context (Environment)

Setting up currently the UMH at a customer in Atlanta

### Possible Solution

Add tutorial on how to add 

```
X509v3 Subject Alternative Name:
IP Address:172.20.22.10
```

to certificate

### Version

v0.8.x

**Comment by Scarjit** [comment]
The solution to this is to extend the gen-rsa command to this:
```
/usr/share/easy-rsa/easyrsa --subject-alt-name="IP:9.9.9.9" gen-req 9.9.9.9 nopass
```
(Assuming you want to create a certificate for 9.9.9.9)
