### ISSUE TITLE
Bug Report: MQTT bridge crashloop

### ISSUE THREAD

**Issue by oarne97** [united-manufacturing-hub/united-manufacturing-hub#866]
### Expected Behavior

MQTT bridge should start

### Current Behavior

MQTT bridge doesn't start and ends up in a crashloop

### Relevant log output

```shell
panic: network Error : dial tcp: lookup united-manufacturing-hub-emqxedge-headless on 10.43.0.10:53: no such host

goroutine 1 [running]:
main.setupMQTT({0xc000018037, 0xc00000e578}, {0x729f58, 0x5}, {0xc000014061, 0x36}, {0xc000018050, 0xd}, 0x0, 0xc000064190, ...)
	/build/cmd/mqtt-bridge/mqtt.go:103 +0x5ae
main.main()
	/build/cmd/mqtt-bridge/main.go:84 +0xb5b
```

### Steps to Reproduce

- Create yaml file
- Perform installation as explained in Docs
- connect with SSH via MobaXterm
- create cluster in lens

### Context (Environment)

MQTT bridge doesn't start

### Version

v0.8.x

**Comment by JeremyTheocharis** [comment]
Probably caused because we switched from EMQXedge to VerneMQ
