### ISSUE TITLE
Bug Report: redis-secret not found

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#876]
### Expected Behavior

mqtt-kafka-bridge should work

### Current Behavior

![image](https://user-images.githubusercontent.com/30755722/155388204-2ad08731-24d2-4b44-b466-9b19b1be668e.png)

### Steps to Reproduce

Install the stack with kafka enabled

### Context (Environment)

Currently integrating at a customer in Atlanta

### Version

v0.8.x

**Comment by Scarjit** [comment]
Hi,

mqtt-kafka-bridge relies on redis, which is enabled by 
 - ```.Values._000_commonConfig.datastorage.enabled```

Sadly this is part of the Chart.yaml, which does not support OR statements.

As a fix, i will move the new message check to memorycache only. (instead of tiered cache)
