### ISSUE TITLE
Messages not persisted on postgres

### ISSUE THREAD

**Issue by edHiga** [united-manufacturing-hub/united-manufacturing-hub#888]
### Expected Behavior

Messages from MQTT are persisted on postgresDB

### Current Behavior

Messages are generated on NodeRed and using the same configuration as usual (no changes on this system since 2 weeks), data is also visible through MQTT Explorer with the correct arragement (ia/factoryinsight) but is not persisted on postgresDB. Lens shows no pod errors
![image](https://user-images.githubusercontent.com/96086143/155570752-6d603c7d-9e22-455c-82c2-954596e8df58.png)

### Steps to Reproduce

System was performing fine, after the WAN connection drop it didn't have the messages persisted anymore

### Context (Environment)

No changes - system was running with the same configuration and parameters before the connection drop. We just want to keep as it was

### Version

not applicable

**Comment by JeremyTheocharis** [comment]
I see that you have restarted VerneMQ. In this case you need to restart mqtt-to-posgtresql as well. Just delete the pod and it will restart.

**Comment by JeremyTheocharis** [comment]
If this does not solve your issue, could you then post the logs of mqtt-to-postgresql?

**Comment by JeremyTheocharis** [comment]
Can we consider your issue closed? Did you manage to fix it?
