### ISSUE TITLE
MQTTBRIDGE: REMOTE_BROKER_SSL_ENABLED is always overwritten by "true" when chart gets deployed

### ISSUE THREAD

**Issue by kruegeralex** [united-manufacturing-hub/united-manufacturing-hub#892]
### Expected Behavior

If I set the variable in the release to false I want the cluster to be built accordingly

### Current Behavior

At the moment it gets set to true when deploying helm chart

### Steps to Reproduce

1. Install via .yaml
2. go to lens > apps > releases and change REMOTE_BROKER_SSL_ENABLED  to false
3. Deploy chart

### Context (Environment)

deploying it in and distributed setup

### Version

v0.8.x

**Comment by JeremyTheocharis** [comment]
Let's ensure that you can control all environment variables from the Helm chart for barcodereader. For barcodereader it is also necessary to specify the port.
