### ISSUE TITLE
Rework /averageCleaningTime, /averageChangeovertime, CalculateAverageStateTime() to be compatible with new datamodel

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#93]
These functions are currently not working as the old datamodel is still hardcoded. Furthermore, change CalculateAverageStateTime() to include sub-states as well (e.g. 100000 is ChangeoverState and this function should include 100001 as well)

**Comment by Scarjit** [comment]
Is this still relevant @JeremyTheocharis  ?
