### ISSUE TITLE
Bug Report: values not showing up in Grafana

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#942]
### Expected Behavior

The distinct processvalues should be shown in Grafana
![image](https://user-images.githubusercontent.com/30755722/160785135-e5108a49-c4e9-4620-93b4-f72c4426977b.png)

### Current Behavior

There are cases when it does not show up at all. The content of the "value" field is still the same even after changing the asset.

Browser returns 502
![image](https://user-images.githubusercontent.com/30755722/160785445-f8931ac9-395d-4356-8c0d-8560dd8ba247.png)

The corresponding SQL query takes at least one minute
![image](https://user-images.githubusercontent.com/30755722/160785760-4a43f412-f44d-4fd7-a3fa-ce28a5d75005.png)

### Steps to Reproduce

1. Have a lot of processvalue entries for that specific asset
2. Open Grafana

### Context (Environment)

Customer in Atlanta

### Possible Solution

Datamodel rework as planned

### Version

v0.8.x

**Comment by Scarjit** [comment]
I have tested adding another index to valuename, and seen speedups of 50-100 times (from 5-6s down to 50-200ms).
This might also be, because with the new index, timescale can apply [skip scan](https://www.timescale.com/blog/how-we-made-distinct-queries-up-to-8000x-faster-on-postgresql/)

**Comment by JeremyTheocharis** [comment]
is this already in a newer version?

**Comment by Scarjit** [comment]
No

**Comment by Scarjit** [comment]
See #1076

**Comment by Scarjit** [comment]
Closed: Fixed in [0.9.6](https://github.com/united-manufacturing-hub/united-manufacturing-hub/releases/tag/v0.9.3)
