### ISSUE TITLE
Kafka and VerneMQ land in Crashloop upon restart

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#975]
### Expected Behavior

When restarting the device Kafka and VerneMQ should start up successfully

### Current Behavior

They land up in a Crashloop

### Steps to Reproduce

Step 1: start Kafka and VerneMQ
Step 2: send a lot of messages through it causing the database to grow big
Step 3: Kubernetes will kill the pod before it fully started (liveness and readyness probes)

### Context (Environment)

Production Environments

### Possible Solution

Increase initialDelay to 300s for both applications. 

### Version

v0.7.x

**Comment by Scarjit** [comment]
Maybe fixed in #979
