### ISSUE TITLE
Bug Report: kafka-to-postgresql starting even though there is no database

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#982]
### Expected Behavior

In this case when there is Kafkam but no database, kafka-to-postgresql should not start

### Current Behavior

It starts

### Steps to Reproduce

datastorage:
    db_password: changeme
    enabled: false
infrastructure:
    kafka:
      enabled: true

### Context (Environment)

v0.9.0-prerelease3

### Version

v0.9.x

**Comment by Scarjit** [comment]
Are you sure, that there is no db ?

The current logic:
https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/654f95754eaa8dd4a5d78ea342069d1325a4c65f/golang/cmd/kafka-to-postgresql/database.go#L22-L65

As you can see, it will try to ping the DB, if this fails, it will panic

**Comment by JeremyTheocharis** [comment]
and then there is a microservice in endlessloop. we should just not start that container.

![image](https://user-images.githubusercontent.com/30755722/164457311-2688977e-82d7-49de-af76-aa2e476f249c.png)
