### ISSUE TITLE
Add microservice calculating state from activity and detectedAnomaly

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#987]
**Is your feature request related to a problem? Please describe.**
We need to calculate the machine state from activity and detectedAnomaly

**Describe the solution you'd like**
So we need a microservice enabled by default subscribing to all machines, watching for activity and detectedAnomaly and then applying the logic.

Logic (proposal, suggestions welcome):

Foreach activity message: if activity is false, then set state to UnspecifiedStopState. If activity is true, then set state to ProducingAtFullSpeedState (use timestamp of incoming activity message as state timestamp)

Foreach detectedAnomaly: 
1. get current activity by fetching last x (e.g., 100) activity messages from kafka, ordering them by timestamp (not timestamp of kafka, but of the message) and then jus taking the last one (reason: it could happen that the messages are unordered). 
2. If activity is true, then ignore message. 
3. If activity is false, then set state to detectedAnomaly (assuming detectedAnomaly is a string containing a valid state number in here: https://docs.umh.app/docs/concepts/state/, need to append documentation to suggest using these state numbers instead of a free-written string)

it should be enabled by default in the helm chart and should be able to disabled in 000_commonConfig

**Describe alternatives you've considered**
Doing this logic in Node-RED and MQTT is impossible as it requires persisting state (where Node-RED is not good in). 

**Additional context**
The logic above is a proposal and can be modified for a more reliable / performant approach. As a second step you could store the activity state also in-memory and only fetch it from kafka during startup. For performance: it should be able to handle 10 incoming activity and detectedAnomaly messages per second.

**Comment by Scarjit** [comment]
Should this application run in "at-least-once" mode, or is it ok to drop messages ?
