### ISSUE TITLE
Bug Report: upgrading pretty difficult

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#992]
### Expected Behavior

I should be able to upgrade from prerelease3 to prerelease4

### Current Behavior

![image](https://user-images.githubusercontent.com/30755722/164719441-b2af5ffe-7348-441e-a80d-36306ddc7bb3.png)

Upgrading fails

### Steps to Reproduce

Upgrade from prerelease3 to prerelease4

### Context (Environment)

Customre project

### Version

v0.9.x

**Comment by JeremyTheocharis** [comment]
Solution: delete the statefulsets barcodereader, sensorconncet and nodered and then perform the upgrade. no data will be lost

**Comment by JeremyTheocharis** [comment]
When using the server stack also deployments need to be deleted

**Comment by Scarjit** [comment]
@Sphingobium This could be a topic for the new doc's ("How-to upgrade the stack")
There is a notion article, but it should be public information

**Comment by Scarjit** [comment]
Documented
